version: "3.8"


networks:
    lucid:

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ${APP_NAME}
        image: app:django
        restart: unless-stopped
        volumes:
            - ./src:/src
        ports:
            -   "8002:8000"
        env_file:
            - .env
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - lucid
        command: python /src/manage.py runserver 0.0.0.0:8000
#        command: gunicorn --bind 0.0.0.0:8000 app.wsgi:application


    mysql:
        image: mysql:8.0
        container_name: ${APP_NAME}_db
        restart: unless-stopped
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - lucid
        volumes:
            - ./mysql_data:/var/lib/mysql
        healthcheck:
            test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u ${DB_USERNAME} --password=${DB_PASSWORD}" ]
            interval: 10s
            timeout: 5s
            retries: 5

